name: Android Build on Tag

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
      - name: Build Release APK
        run: ./gradlew assembleRelease
      - name: Extract Tag Name
        id: get_tag_name
        run: echo "::set-output name=TAG_NAME::${GITHUB_REF#refs/tags/}"
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app-release-${{ steps.get_tag_name.outputs.TAG_NAME }}.apk
          path: app/build/outputs/apk/release/app-release.apk
